#file: noinspection SpellCheckingInspection
name: Build and publish project artifacts on platforms
on:
  release:
    types:
      - published
  workflow_dispatch:

env:
  cobblemon: 1.7.3

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    strategy:
      matrix:
        # Use these Java versions
        java: [
          21,    # Current Java LTS
        ]
    outputs:
      version: ${{ steps.version.outputs.MOD_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Build
        uses: burrunan/gradle-cache-action@v3
        with:
          read-only: true
          arguments: buildMod
      - name: Capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: build/libs/
      - name: Save version output
        id: version
        run: echo "MOD_VERSION=$(gradle currentVersion -q -Prelease.quiet)" >> "$GITHUB_OUTPUT"

  publish:
    needs: build
    runs-on: ubuntu-22.04
    env:
      curseforge_id: 1196570
      modrinth_id: eF8kqlHd
    strategy:
      matrix:
        loader: [
          fabric,
          neoforge,
        ]
    steps:
      - name: Retrieve build artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: build/libs/
      - name: Publish ${{ matrix.loader }} version (CurseForge/Modrinth)
        uses: Kira-NT/mc-publish@v3.3
        with:
          name: "Rad Gyms ${{ needs.build.outputs.version }} for Cobblemon ${{ env.cobblemon }}"
          version: "${{ env.cobblemon }}_${{ needs.build.outputs.version }}"
          version-type: release

          curseforge-id: ${{ env.curseforge_id }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          modrinth-id: ${{ env.curseforge_id }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: |
            build/libs/rad-gyms-${{ matrix.loader }}-${{ needs.build.outputs.version }}.jar
            build/libs/rad-gyms-${{ matrix.loader }}-${{ needs.build.outputs.version }}-sources.jar 

          loaders: ${{ matrix.loader }}

          game-versions: 1.21.1
          java: 21
